In [37]:
import numpy as np
import matplotlib.pyplot as plt

In [38]:
C = np.array([20.1, 20.8, 21.9, 22.5, 22.7, 22.3, 21.8, 21.2, 20.9, 20.1])

In [39]:
print(C)

[20.1 20.8 21.9 22.5 22.7 22.3 21.8 21.2 20.9 20.1]


In [40]:
F = C * 9 / 5 + 32

In [41]:
print(F)

[68.18 69.44 71.42 72.5  72.86 72.14 71.24 70.16 69.62 68.18]


In [51]:
%matplotlib inline
plt.plot(C)
plt.title('Temperatures in Fahrenheit')
plt.show()

In [43]:
#creation of arrays
a = np.arange(1, 10)

In [44]:
print(a)

[1 2 3 4 5 6 7 8 9]


In [45]:
x = range(1, 10)
print(x)
print(list(x))

range(1, 10)
[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [46]:
print(np.linspace(1, 10))
print(np.linspace(1, 10, 7))
print(np.linspace(1, 10, 7, endpoint=False))

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
[ 1.   2.5  4.   5.5  7.   8.5 10. ]
[1.         2.28571429 3.57142857 4.85714286 6.14285714 7.42857143
 8.71428571]


In [47]:
samples, spacing = np.linspace(1, 10, 7, retstep=True)
print(samples)
print(spacing)

[ 1.   2.5  4.   5.5  7.   8.5 10. ]
1.5


In [48]:
# zero dimensional array
x = np.array(43)
print(x)
print(type(x))
print(np.ndim(x))

43
<class 'numpy.ndarray'>
0


In [49]:
# 4 dimensional array
A = np.array([
    [
        [[1, 2, 3], [1, 2, 3]],
        [[1, 2, 3], [1, 2, 3]]
    ],
    [
        [[1, 2, 5], [1, 2, 3]],
        [[1, 2, 3], [1, 2, 3]]
    ]
])

print(np.ndim(A))
print(A.shape)
print(A[1][0][0][2])
print(A[1, 0, 0, 2])
print(A[0, 0, :])

4
(2, 2, 2, 3)
5
5
[[1 2 3]
 [1 2 3]]
