In [1]:
import numpy as np

In [5]:
one = np.arange(0, 10)
print(one)
# indexing
print(one[1])
# slicing
print(one[1:])

[0 1 2 3 4 5 6 7 8 9]
1
[1 2 3 4 5 6 7 8 9]


In [14]:
two = np.arange(0, 10).reshape(2, 5)
print(two)
# indexing
print(two[1, 2])
# slicing
print(two[1:, 2:])

[[0 1 2 3 4]
 [5 6 7 8 9]]
7
[[7 8 9]]


In [25]:
three = np.arange(0, 15).reshape(1, 3, 5)
print(three)
# indexing
print(three[0, 1, 2])
# slicing
print(three[:,1:, 2:])

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]]
7
[[[ 7  8  9]
  [12 13 14]]]


In [28]:
three = np.arange(0, 24).reshape(2, 3, 4)
print(three)
print(three[1, 1, 3])
print(three[1:, 1:, 1:])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
19
[[[17 18 19]
  [21 22 23]]]


In [32]:
four = np.linspace(1, 50).reshape(2, 1, 5, 5)
print(four)
# indexing
print(four[1, 0, 0, 2])
print(four[1:, 0:, 0:3, 2:])

[[[[ 1.  2.  3.  4.  5.]
   [ 6.  7.  8.  9. 10.]
   [11. 12. 13. 14. 15.]
   [16. 17. 18. 19. 20.]
   [21. 22. 23. 24. 25.]]]


 [[[26. 27. 28. 29. 30.]
   [31. 32. 33. 34. 35.]
   [36. 37. 38. 39. 40.]
   [41. 42. 43. 44. 45.]
   [46. 47. 48. 49. 50.]]]]
28.0
[[[[28. 29. 30.]
   [33. 34. 35.]
   [38. 39. 40.]]]]
